name: Increment Tag Version

on:
  push:
    branches:
      - release

jobs:
    version:
        name: Increment Tag Version
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get next version
              uses: reecetech/version-increment@2023.10.2
              id: version
              with:
                release_branch: release
                scheme: semver
                increment: patch

            - run: git tag ${{ steps.version.outputs.version }}
            - run: git push origin --tags
    