name: Version Increment

on:
  push:
    branches:
      - deployment

jobs:
    version:
        name: Version Increment
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Get next version
              uses: reecetech/version-increment@2023.10.2
              id: version
              with:
                release_branch: deployment
                scheme: semver
                increment: patch

            - name: Build image
              uses: docker/build-push-action@v2
              with:
                push: false
                tags: "example/application:${{ steps.version.outputs.version }}"
                context: .